### PR TITLE
/status: give feedback to user on status change

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by JFreegman** [comment]
I'm not sure that I see the purpose for this. Can you explain?

**Comment by ghost** [comment]
Yes, the purpose is having the UI give feedback, that that command succeeded. I feel like this is generally a good idea that the UI gives feedback to users. Especially when there is no other indicator on the user's status on some views, like the chat window.

I don't know about other people, but when I first used this command, I expected any kind of feedback of the outcome of that command. But there was nothing, so I wasn't sure if it worked, or what, and went to check on the home window.
Had there been a status indicator on chat windows, there would have been no problem.

Do you see my point?

I see my PR as an easy, temporary solution, but in the long run I think that including the status in chat windows is the proper way to do this. But, would have to think about a good spot for the status, first.

It's also easy to forget about your status, when you don't see it. I don't know how much time people spend on the home window, but probably not so much.
Not that a wrong status matters in the universe, but I think a wrong status is pointless, too.

These are my thoughts and notes on that matter.

**Comment by ghost** [comment]
Thank you.

May I know your opinion on including status indicator in chat windows (in favor of this system message)?

**Comment by JFreegman** [comment]
I don't think it's a bad idea, but I'm not sure how to do it without making the interface ugly. I'll think about it some more.

**Comment by ghost** [comment]
I'll think about it, too.

**Pull request merged**
