### PR TITLE
added archlinux package link

### PR DESCRIPTION
**Pull request by wilzbach**

### CODE REVIEW

**Comment by zetok** [comment]
as of now, AUR is still no supported.

Correct link would be to supported PKGBUILD in https://github.com/Tox/arch-repo-tox

**Comment by urras** [comment]
@zetok toxic-git is now maintained by @haavardp, should this be updated?

**Comment by zetok** [comment]
@urras why? AFAIK AUR is still not supported..?

**Comment by JFreegman** [comment]
Unofficial packages belong on the wiki. Talk to someone in IRC about adding it.

**Pull request closed without merging**
