### PR TITLE
Makefile: save user-defined variables

### PR DESCRIPTION
**Pull request by Ansa89**

### CODE REVIEW

**Comment by Ansa89** [comment]
@zetok: this is what we discussed on IRC.
Please test it and comment.

**Comment by JFreegman** [comment]
Could someone give a general description of this PR?

**Comment by JFreegman** [comment]
I guess this one is stale

**Comment by zetok** [comment]
@JFreegman 
It's not stale.

Currently

```
make PREFIX="/rawr"
make install
```

installs toxic into `/usr/local/`.

With PR:

```
make PREFIX="/rawr"
make install
```

installs toxic into `/rawr`.

Dunno, on one hand PR simplifies stuff, on the other, it might add some complexity to troubleshooting, given that "user" might not be aware that variables passed to `make` are being saved to use with `make install`.

**Pull request closed without merging**
